# Assumption-Evidence Table
 
| No. | Team Assumption | Evidence Collected | Evidence Type | Strength | Decision |
|---:|---|---|---|---|---|
| 1 | Students and lecturers struggle because the PDF timetable does not update when classes are cancelled, moved, or relocated. | Multiple respondents described real incidents: a room changed to a different building, a class cancelled with no PDF update, an exam room change, and a room double-booked. Several said the timetable "doesn't update automatically when a class is canceled or postponed." | Survey | Strong | Keep |
| 2 | Students currently rely on informal channels (group chats, asking lecturers, memory) instead of an official, reliable source. | Workarounds reported included confirming in class group chats, asking classmates, contacting the lecturer directly, and relying on memory. One lecturer said they "informed the students via LINE group chat" themselves when the PDF didn't reflect changes. | Survey | Strong | Keep |
| 3 | A real-time digital timetable with notifications would be valuable enough that students and lecturers would switch from the current PDF. | 11 of 15 respondents rated the potential improvement 7/10 or higher, and 9 selected "Definitely" when asked if they would switch to a free digital version with live updates. One respondent wrote they "really hope this digital timetable launches soon." | Survey | Strong | Keep |
| 4 | All users experience this problem at a similarly high frequency and severity. | Responses varied significantly: some reported "Almost never" experiencing issues and rated improvement as low as 2/10, while others reported issues "All the time" and rated improvement as high as 10/10. One respondent said they currently have no problems with the PDF at all. | Survey | Moderate | Revise |
| 5 | Push notifications for schedule changes are the single most desired feature. | Several respondents specifically asked for "push notifications," "instant push notifications," or "instant notification when the schedule changes," but others asked for different features such as calendar sync, a room search function, or an auto reminder, showing the desired feature is not fully consistent across users. | Survey | Moderate | Revise |
| 6 | Staff and lecturers face the same core problem as students, just from a different angle. | One staff respondent described repeatedly explaining room changes to students individually due to no shared source of truth, and one lecturer described losing teaching time relocating a class due to a room double-booking. Only two non-student respondents were collected so far. | Survey | Weak/Moderate | Revise |
